services:
  media-pipeline-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:8081"
        DIST_DIR: "dist"
    image: media-web:latest
    container_name: media-pipeline-web
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - media-pipeline-network

networks:
  media-pipeline-network:
    driver: bridge
